### ISSUE TITLE
claims/scope - user_impersonation (from code samples) vs. access_as_user (from documentation)

### ISSUE THREAD

**Issue by rualdventer** [Azure-Samples/active-directory-dotnet-native-desktop#36]
Hi guys,

In the documentation and code samples found at the below links, the code samples look for a claim value "user_impersonation" in TodoListController.cs, and when creating the permissions on the app registration the name "access_as_user" is specified.

https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v1-dotnet-webapi

https://github.com/azure-samples/active-directory-dotnet-native-desktop

When following steps outlined in the documentation at the second link, authentication is successful but exceptions are thrown in the Get and Put methods in TodoListController, reason being is the code samples find the first claim with type "http://schemas.microsoft.com/identity/claims/scope" and is expecting it to have the value "user_impersonation", else it throws an exception.  However, the only claim of that type I can see returned is the "access_as_user" one created as part of the setup, needless to say, if I change the code to expect "access_as_user" it works.

Is it correct that the code samples are expecting a claim with value "user_impersonation", or should it be the "access_as_user" permission created during the documentation?

Mind you this is the first time I'm trying to authenticate against Azure AD, so I apologize in advance if this is not an issue and the problem is my lack of understanding/knowledge on the subject.

Regards

**Comment by TiagoBrenck** [comment]
Hello @rualdventer, thanks for pointing that out.

**Is it correct that the code samples are expecting a claim with value "user_impersonation", or should it be the "access_as_user" permission created during the documentation?**
It is up to you. This scope name could be anything you want because it is a custom scope, as long as your code check for that same scope name that you created.

About the difference between the documentation and the code, this was a sync problem on our end. I will update the documentation. 

Thanks
